#pragma once

#define POINTER_TO_ATTRIBUTES 0x15DCD9415
#define OFFSET_ABILITY -0x78
#define OFFSET_POSITIONS -0x70
#define OFFSET_ATTRIBUTES -0x61
#define OFFSET_ID 0x0C
#define OFFSET_PERSONALITY 0x78
#define PERSONALITY_ADAPTABILITY 0
#define ABILITY_CA 0
#define ABILITY_PA 2
#define PERSONALITY_AMBITION 1
#define PERSONALITY_LOYALTY 2
#define PERSONALITY_PRESSURE 3
#define PERSONALITY_PROFESSIONALISM 4
#define PERSONALITY_SPORTSMANSHIP 5
#define PERSONALITY_TEMPERAMENT 6
#define PERSONALITY_CONTROVERSY 7
