#pragma once

#define POINTER_TO_ATTRIBUTES 0x15DCD9415
// #define POINTER_TO_MY_TEAM 0x42f8ac8
// #define POINTER_TO_MY_TEAM 0x42f8bb8
// #define POINTER_TO_MY_TEAM 0x42f9508
// #define POINTER_TO_CURRENT_TEAM 0x4302588
// #define POINTER_TO_CURRENT_TEAM 0x43025c8
#define POINTER_TO_CURRENT_TEAM 0x43025f0
#define POINTER_TO_CURRENT_DATETIME 0x14631D5BC

#define OFFSET_DOB 0x44
#define OFFSET_FORENAME 0x58
#define OFFSET_SURNAME 0x60
#define OFFSET_ABILITY -0x78
#define OFFSET_POSITIONS -0x70
#define OFFSET_ATTRIBUTES -0x61
#define OFFSET_ID 0x0C
#define OFFSET_PERSONALITY 0x78

#define ABILITY_CA 0
#define ABILITY_PA 2

#define ATTRIBUTES_INJURY_PRONENESS 48
#define ATTRIBUTES_DETERMINATION 51

#define PERSONALITY_ADAPTABILITY 0
#define PERSONALITY_AMBITION 1
#define PERSONALITY_LOYALTY 2
#define PERSONALITY_PRESSURE 3
#define PERSONALITY_PROFESSIONALISM 4
#define PERSONALITY_SPORTSMANSHIP 5
#define PERSONALITY_TEMPERAMENT 6
#define PERSONALITY_CONTROVERSY 7
